#!/bin/sh

PYTHON=`which python33 2>/dev/null`

if [ "x$PYTHON" = "x" ]
then
  PYTHON=`which python3.3 2>/dev/null`
fi

if [ "x$PYTHON" = "x" ]
then
  PYTHON=`which python3 2>/dev/null`
fi

if [ "x$PYTHON" = "x" ]
then
  PYTHON=`which python 2>/dev/null`
fi

DIR=$(dirname $0)
$PYTHON $DIR/atrium-fetch.py "$@"
